name = "Flatten"
uuid = "4c728ea3-d9ee-5c9a-9642-b6f7d7dc04fa"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.2.0"

[deps]
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"

[compat]
julia = "0.7, 1.0"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BenchmarkTools", "Test"]
